name: Hello

on: 
  - push
  - workflow_dispatch

jobs: 
  hello:
    name: Hello code base
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "hello"
      - name: Print java version
        run: java --version
      

