name: Hello

on: 
  - push
  - workflow_dispatch

jobs: 
  hello:
    name: Hello code base
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "hello"
      - name: Print java version
        run: java --version
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2  
      - name: installing node.js and npm
        run: |
          sudo apt-get install -y nodejs
          sudo apt-get install -y npm
      - name: installing appium 
        run: sudo npm install -g appium 
      - name: appium
        run: |
          appium & 
          echo "running some tests"